#261 Pagination and basic Filter.
pimcore/studio-backend-bundle pull request #273
Opened 2024-07-23 12:25 UTC by martineiber

## Changes in this pull request
Part of #261

## Additional info

2024-07-23 14:30 UTC, lukmzig commented on src/Asset/Service/AssetService.php
> +            throw new NotFoundException('folder', $id);
We could use here enum value :)
https://github.com/pimcore/studio-backend-bundle/blob/1.x/src/Util/Constants/ElementTypes.php#L34

2024-07-23 14:30 UTC, lukmzig commented on doc/03_Grid.md
> +includeDescendants` is a boolean value to include the descendants of the current item.
```suggestion
`includeDescendants` is a boolean value to include the descendants of the current item.
```

2024-07-23 14:31 UTC, lukmzig commented on src/DataIndex/Grid/GridSearch.php
> +     * @throws NotFoundException
```suggestion
     * @throws SearchException|NotFoundException
```

2024-07-23 14:32 UTC, lukmzig commented on src/Grid/Service/GridService.php
> +                'asset'
We can also use element types enum here :)

2024-07-23 14:33 UTC, lukmzig requested changes
Some small changes, the rest :seal:

2024-07-24 06:46 UTC, martineiber commented on src/Asset/Service/AssetService.php
> +            throw new NotFoundException('folder', $id);
Thanks for the hint.. Changed it :)

2024-07-24 06:51 UTC, lukmzig approved these changes

2024-07-24 07:15 UTC, merged