[Task] Add batch edit based on folder ids
pimcore/studio-backend-bundle pull request #496
Opened 2024-10-16 08:03 UTC by mattamon

## Changes in this pull request
Resolves #494 

## Additional info
Adding new endpoint to batch edit data from elements based on folder id

2024-10-16 12:29 UTC, lukmzig requested changes
Rest looks LGTM :seal:

2024-10-16 12:29 UTC, lukmzig commented on src/Asset/Controller/PatchFolderController.php
> +        summary: 'asset_patch_folder_by_id_summary',
Could we maybe add translations for the new controller action? :)

2024-10-16 12:58 UTC, mattamon commented on src/Asset/Controller/PatchFolderController.php
> +        summary: 'asset_patch_folder_by_id_summary',
haha yeah of course I forgot the translations. I will add them! :D

2024-10-17 06:37 UTC, mattamon commented
@lukmzig sorry I forgot to add the filters so I had to refactor it again. 
I do however see a problem with the constants for the Generic Execution Engine. I do not like the current position, so I will move it to a more fitting place with a separate PR if that is okay.

2024-10-17 06:40 UTC, lukmzig approved these changes

2024-10-17 06:49 UTC, merged